const GAME_CONFIG = {
    "categories": [
        {
            "id": "1",
            "name": "Human Deaths",
            "description": "Annual number of human fatalities caused by this animal species (higher score = more dangerous to humans)"
        },
        {
            "id": "2",
            "name": "Hair Density",
            "description": "Density and coverage of fur/hair on the animal's body (higher score = denser fur/more coverage)"
        },
        {
            "id": "3",
            "name": "Top Speed",
            "description": "Maximum recorded speed of the animal (higher score = faster movement capability)"
        },
        {
            "id": "4",
            "name": "Lifespan",
            "description": "Average or maximum lifespan in years (higher score = longer-lived species)"
        },
        {
            "id": "5",
            "name": "Population",
            "description": "Current global population size and conservation status (higher score = larger/more stable populations)"
        },
        {
            "id": "6",
            "name": "Habitat Extent",
            "description": "Geographic range and area of habitat distribution (higher score = wider distribution across regions)"
        },
        {
            "id": "7",
            "name": "Relative Strength",
            "description": "Physical strength relative to body size and weight (higher score = stronger pound-for-pound)"
        },
        {
            "id": "8",
            "name": "Consumption by Humans",
            "description": "Degree to which humans consume this species as food globally (higher score = more heavily consumed)"
        }
    ],
    "animals": {
        "Mosquito": {
            "1": 100,
            "2": 5,
            "3": 2,
            "4": 3,
            "5": 100,
            "6": 95,
            "7": 8,
            "8": 0,
            "image": "images/mosquito.jpg"
        },
        "Human": {
            "1": 75,
            "2": 45,
            "3": 45,
            "4": 95,
            "5": 100,
            "6": 100,
            "7": 42,
            "8": 0,
            "image": "images/human.jpg"
        },
        "Snake": {
            "1": 65,
            "2": 8,
            "3": 30,
            "4": 35,
            "5": 85,
            "6": 90,
            "7": 45,
            "8": 15,
            "image": "images/snake.jpg"
        },
        "Dog": {
            "1": 55,
            "2": 65,
            "3": 55,
            "4": 18,
            "5": 95,
            "6": 100,
            "7": 48,
            "8": 35,
            "image": "images/dog.jpg"
        },
        "Tsetse Fly": {
            "1": 50,
            "2": 5,
            "3": 8,
            "4": 5,
            "5": 60,
            "6": 45,
            "7": 10,
            "8": 0,
            "image": "images/tsetse_fly.jpg"
        },
        "Freshwater Snail": {
            "1": 48,
            "2": 2,
            "3": 1,
            "4": 12,
            "5": 75,
            "6": 55,
            "7": 5,
            "8": 5,
            "image": "images/freshwater_snail.jpg"
        },
        "Assassin Bug": {
            "1": 45,
            "2": 6,
            "3": 5,
            "4": 8,
            "5": 70,
            "6": 60,
            "7": 12,
            "8": 0,
            "image": "images/assassin_bug.jpg"
        },
        "Ascaris Roundworm": {
            "1": 42,
            "2": 1,
            "3": 1,
            "4": 2,
            "5": 80,
            "6": 75,
            "7": 3,
            "8": 0,
            "image": "images/ascaris_roundworm.jpg"
        },
        "Tapeworm": {
            "1": 38,
            "2": 0,
            "3": 0,
            "4": 25,
            "5": 70,
            "6": 70,
            "7": 2,
            "8": 0,
            "image": "images/tapeworm.jpg"
        },
        "Crocodile": {
            "1": 35,
            "2": 10,
            "3": 20,
            "4": 90,
            "5": 45,
            "6": 65,
            "7": 85,
            "8": 25,
            "image": "images/crocodile.jpg"
        },
        "Hippopotamus": {
            "1": 32,
            "2": 15,
            "3": 35,
            "4": 55,
            "5": 40,
            "6": 35,
            "7": 88,
            "8": 8,
            "image": "images/hippopotamus.jpg"
        },
        "Elephant": {
            "1": 28,
            "2": 20,
            "3": 32,
            "4": 85,
            "5": 42,
            "6": 70,
            "7": 95,
            "8": 5,
            "image": "images/elephant.jpg"
        },
        "Lion": {
            "1": 12,
            "2": 55,
            "3": 58,
            "4": 18,
            "5": 35,
            "6": 40,
            "7": 75,
            "8": 3,
            "image": "images/lion.jpg"
        },
        "Cape Buffalo": {
            "1": 25,
            "2": 52,
            "3": 54,
            "4": 30,
            "5": 55,
            "6": 48,
            "7": 78,
            "8": 18,
            "image": "images/cape_buffalo.jpg"
        },
        "Scorpion": {
            "1": 18,
            "2": 8,
            "3": 12,
            "4": 10,
            "5": 75,
            "6": 85,
            "7": 35,
            "8": 0,
            "image": "images/scorpion.jpg"
        },
        "Jellyfish": {
            "1": 15,
            "2": 0,
            "3": 5,
            "4": 15,
            "5": 85,
            "6": 90,
            "7": 15,
            "8": 2,
            "image": "images/jellyfish.jpg"
        },
        "Tiger": {
            "1": 14,
            "2": 62,
            "3": 58,
            "4": 22,
            "5": 15,
            "6": 45,
            "7": 82,
            "8": 1,
            "image": "images/tiger.jpg"
        },
        "Bear": {
            "1": 10,
            "2": 90,
            "3": 48,
            "4": 35,
            "5": 48,
            "6": 75,
            "7": 85,
            "8": 8,
            "image": "images/bear.jpg"
        },
        "Leopard": {
            "1": 8,
            "2": 58,
            "3": 55,
            "4": 18,
            "5": 38,
            "6": 62,
            "7": 72,
            "8": 2,
            "image": "images/leopard.jpg"
        },
        "Wolf": {
            "1": 6,
            "2": 75,
            "3": 52,
            "4": 16,
            "5": 45,
            "6": 70,
            "7": 68,
            "8": 5,
            "image": "images/wolf.jpg"
        },
        "Shark": {
            "1": 5,
            "2": 5,
            "3": 45,
            "4": 45,
            "5": 52,
            "6": 88,
            "7": 78,
            "8": 22,
            "image": "images/shark.jpg"
        },
        "Bee": {
            "1": 22,
            "2": 15,
            "3": 25,
            "4": 1,
            "5": 90,
            "6": 95,
            "7": 18,
            "8": 2,
            "image": "images/bee.jpg"
        },
        "Wasp": {
            "1": 20,
            "2": 12,
            "3": 28,
            "4": 1,
            "5": 88,
            "6": 92,
            "7": 20,
            "8": 0,
            "image": "images/wasp.jpg"
        },
        "Spider": {
            "1": 8,
            "2": 18,
            "3": 15,
            "4": 5,
            "5": 92,
            "6": 98,
            "7": 22,
            "8": 0,
            "image": "images/spider.jpg"
        },
        "Ant": {
            "1": 2,
            "2": 8,
            "3": 8,
            "4": 4,
            "5": 98,
            "6": 98,
            "7": 55,
            "8": 1,
            "image": "images/ant.jpg"
        },
        "Cheetah": {
            "1": 1,
            "2": 48,
            "3": 100,
            "4": 14,
            "5": 22,
            "6": 35,
            "7": 55,
            "8": 0,
            "image": "images/cheetah.jpg"
        },
        "Pronghorn": {
            "1": 0,
            "2": 52,
            "3": 95,
            "4": 16,
            "5": 58,
            "6": 42,
            "7": 52,
            "8": 5,
            "image": "images/pronghorn.jpg"
        },
        "Springbok": {
            "1": 0,
            "2": 48,
            "3": 88,
            "4": 12,
            "5": 65,
            "6": 38,
            "7": 48,
            "8": 8,
            "image": "images/springbok.jpg"
        },
        "Wildebeest": {
            "1": 2,
            "2": 50,
            "3": 78,
            "4": 25,
            "5": 68,
            "6": 42,
            "7": 65,
            "8": 12,
            "image": "images/wildebeest.jpg"
        },
        "Zebra": {
            "1": 1,
            "2": 48,
            "3": 62,
            "4": 28,
            "5": 62,
            "6": 52,
            "7": 58,
            "8": 4,
            "image": "images/zebra.jpg"
        },
        "Giraffe": {
            "1": 0,
            "2": 28,
            "3": 55,
            "4": 32,
            "5": 48,
            "6": 45,
            "7": 68,
            "8": 2,
            "image": "images/giraffe.jpg"
        },
        "Gorilla": {
            "1": 3,
            "2": 88,
            "3": 32,
            "4": 48,
            "5": 18,
            "6": 28,
            "7": 88,
            "8": 0,
            "image": "images/gorilla.jpg"
        },
        "Chimpanzee": {
            "1": 4,
            "2": 72,
            "3": 35,
            "4": 55,
            "5": 32,
            "6": 38,
            "7": 75,
            "8": 0,
            "image": "images/chimpanzee.jpg"
        },
        "Orangutan": {
            "1": 1,
            "2": 78,
            "3": 8,
            "4": 65,
            "5": 12,
            "6": 22,
            "7": 72,
            "8": 0,
            "image": "images/orangutan.jpg"
        },
        "Rhinoceros": {
            "1": 5,
            "2": 18,
            "3": 42,
            "4": 58,
            "5": 28,
            "6": 38,
            "7": 90,
            "8": 1,
            "image": "images/rhinoceros.jpg"
        },
        "Water Buffalo": {
            "1": 8,
            "2": 42,
            "3": 45,
            "4": 32,
            "5": 62,
            "6": 55,
            "7": 92,
            "8": 45,
            "image": "images/water_buffalo.jpg"
        },
        "Bison": {
            "1": 6,
            "2": 85,
            "3": 52,
            "4": 28,
            "5": 42,
            "6": 38,
            "7": 85,
            "8": 28,
            "image": "images/bison.jpg"
        },
        "Yak": {
            "1": 2,
            "2": 92,
            "3": 38,
            "4": 28,
            "5": 55,
            "6": 32,
            "7": 78,
            "8": 35,
            "image": "images/yak.jpg"
        },
        "Moose": {
            "1": 4,
            "2": 72,
            "3": 48,
            "4": 25,
            "5": 58,
            "6": 52,
            "7": 75,
            "8": 15,
            "image": "images/moose.jpg"
        },
        "Elk": {
            "1": 3,
            "2": 68,
            "3": 52,
            "4": 22,
            "5": 62,
            "6": 58,
            "7": 72,
            "8": 20,
            "image": "images/elk.jpg"
        },
        "Deer": {
            "1": 2,
            "2": 58,
            "3": 55,
            "4": 18,
            "5": 82,
            "6": 85,
            "7": 52,
            "8": 65,
            "image": "images/deer.jpg"
        },
        "Reindeer": {
            "1": 1,
            "2": 82,
            "3": 58,
            "4": 22,
            "5": 68,
            "6": 48,
            "7": 62,
            "8": 42,
            "image": "images/reindeer.jpg"
        },
        "Caribou": {
            "1": 0,
            "2": 78,
            "3": 62,
            "4": 18,
            "5": 65,
            "6": 35,
            "7": 58,
            "8": 32,
            "image": "images/caribou.jpg"
        },
        "Antelope": {
            "1": 0,
            "2": 42,
            "3": 72,
            "4": 16,
            "5": 72,
            "6": 68,
            "7": 55,
            "8": 22,
            "image": "images/antelope.jpg"
        },
        "Gazelle": {
            "1": 0,
            "2": 38,
            "3": 82,
            "4": 14,
            "5": 68,
            "6": 58,
            "7": 48,
            "8": 12,
            "image": "images/gazelle.jpg"
        },
        "Impala": {
            "1": 0,
            "2": 42,
            "3": 78,
            "4": 16,
            "5": 72,
            "6": 42,
            "7": 52,
            "8": 8,
            "image": "images/impala.jpg"
        },
        "Kudu": {
            "1": 1,
            "2": 48,
            "3": 55,
            "4": 18,
            "5": 58,
            "6": 42,
            "7": 62,
            "8": 5,
            "image": "images/kudu.jpg"
        },
        "Eland": {
            "1": 0,
            "2": 45,
            "3": 52,
            "4": 25,
            "5": 62,
            "6": 45,
            "7": 68,
            "8": 10,
            "image": "images/eland.jpg"
        },
        "Oryx": {
            "1": 0,
            "2": 38,
            "3": 58,
            "4": 22,
            "5": 55,
            "6": 38,
            "7": 65,
            "8": 4,
            "image": "images/oryx.jpg"
        },
        "Gemsbok": {
            "1": 0,
            "2": 42,
            "3": 58,
            "4": 22,
            "5": 58,
            "6": 35,
            "7": 62,
            "8": 3,
            "image": "images/gemsbok.jpg"
        },
        "Chicken": {
            "1": 0,
            "2": 65,
            "3": 15,
            "4": 8,
            "5": 98,
            "6": 100,
            "7": 12,
            "8": 98,
            "image": "images/chicken.jpg"
        },
        "Turkey": {
            "1": 0,
            "2": 72,
            "3": 28,
            "4": 12,
            "5": 95,
            "6": 85,
            "7": 22,
            "8": 85,
            "image": "images/turkey.jpg"
        },
        "Duck": {
            "1": 0,
            "2": 88,
            "3": 75,
            "4": 12,
            "5": 92,
            "6": 95,
            "7": 18,
            "8": 72,
            "image": "images/duck.jpg"
        },
        "Goose": {
            "1": 1,
            "2": 85,
            "3": 88,
            "4": 28,
            "5": 88,
            "6": 92,
            "7": 25,
            "8": 58,
            "image": "images/goose.jpg"
        },
        "Pig": {
            "1": 3,
            "2": 25,
            "3": 18,
            "4": 22,
            "5": 95,
            "6": 92,
            "7": 58,
            "8": 95,
            "image": "images/pig.jpg"
        },
        "Sheep": {
            "1": 1,
            "2": 95,
            "3": 28,
            "4": 15,
            "5": 95,
            "6": 88,
            "7": 32,
            "8": 88,
            "image": "images/sheep.jpg"
        },
        "Goat": {
            "1": 2,
            "2": 82,
            "3": 32,
            "4": 18,
            "5": 95,
            "6": 92,
            "7": 38,
            "8": 82,
            "image": "images/goat.jpg"
        },
        "Cow": {
            "1": 4,
            "2": 38,
            "3": 35,
            "4": 25,
            "5": 98,
            "6": 95,
            "7": 72,
            "8": 92,
            "image": "images/cow.jpg"
        },
        "Horse": {
            "1": 3,
            "2": 52,
            "3": 75,
            "4": 35,
            "5": 88,
            "6": 95,
            "7": 75,
            "8": 12,
            "image": "images/horse.jpg"
        },
        "Donkey": {
            "1": 1,
            "2": 48,
            "3": 52,
            "4": 42,
            "5": 85,
            "6": 78,
            "7": 68,
            "8": 8,
            "image": "images/donkey.jpg"
        },
        "Llama": {
            "1": 0,
            "2": 88,
            "3": 45,
            "4": 25,
            "5": 72,
            "6": 22,
            "7": 55,
            "8": 15,
            "image": "images/llama.jpg"
        },
        "Alpaca": {
            "1": 0,
            "2": 95,
            "3": 42,
            "4": 22,
            "5": 78,
            "6": 18,
            "7": 48,
            "8": 18,
            "image": "images/alpaca.jpg"
        },
        "Camel": {
            "1": 2,
            "2": 72,
            "3": 48,
            "4": 58,
            "5": 72,
            "6": 52,
            "7": 78,
            "8": 28,
            "image": "images/camel.jpg"
        },
        "Dromedary": {
            "1": 1,
            "2": 68,
            "3": 52,
            "4": 55,
            "5": 68,
            "6": 48,
            "7": 75,
            "8": 22,
            "image": "images/dromedary.jpg"
        },
        "Kangaroo": {
            "1": 0,
            "2": 35,
            "3": 68,
            "4": 18,
            "5": 75,
            "6": 32,
            "7": 65,
            "8": 32,
            "image": "images/kangaroo.jpg"
        },
        "Wallaby": {
            "1": 0,
            "2": 42,
            "3": 52,
            "4": 15,
            "5": 72,
            "6": 28,
            "7": 52,
            "8": 8,
            "image": "images/wallaby.jpg"
        },
        "Koala": {
            "1": 0,
            "2": 88,
            "3": 5,
            "4": 22,
            "5": 38,
            "6": 12,
            "7": 28,
            "8": 0,
            "image": "images/koala.jpg"
        },
        "Wombat": {
            "1": 0,
            "2": 78,
            "3": 35,
            "4": 28,
            "5": 52,
            "6": 18,
            "7": 58,
            "8": 2,
            "image": "images/wombat.jpg"
        },
        "Platypus": {
            "1": 1,
            "2": 92,
            "3": 8,
            "4": 25,
            "5": 48,
            "6": 8,
            "7": 42,
            "8": 0,
            "image": "images/platypus.jpg"
        },
        "Echidna": {
            "1": 0,
            "2": 85,
            "3": 12,
            "4": 65,
            "5": 62,
            "6": 28,
            "7": 48,
            "8": 0,
            "image": "images/echidna.jpg"
        },
        "Opossum": {
            "1": 0,
            "2": 72,
            "3": 15,
            "4": 8,
            "5": 82,
            "6": 75,
            "7": 35,
            "8": 1,
            "image": "images/opossum.jpg"
        },
        "Raccoon": {
            "1": 0,
            "2": 78,
            "3": 25,
            "4": 12,
            "5": 88,
            "6": 82,
            "7": 45,
            "8": 3,
            "image": "images/raccoon.jpg"
        },
        "Badger": {
            "1": 1,
            "2": 82,
            "3": 28,
            "4": 18,
            "5": 75,
            "6": 68,
            "7": 62,
            "8": 2,
            "image": "images/badger.jpg"
        },
        "Otter": {
            "1": 0,
            "2": 95,
            "3": 18,
            "4": 22,
            "5": 58,
            "6": 55,
            "7": 52,
            "8": 5,
            "image": "images/otter.jpg"
        },
        "Beaver": {
            "1": 0,
            "2": 92,
            "3": 12,
            "4": 28,
            "5": 72,
            "6": 52,
            "7": 58,
            "8": 4,
            "image": "images/beaver.jpg"
        },
        "Squirrel": {
            "1": 0,
            "2": 78,
            "3": 32,
            "4": 12,
            "5": 95,
            "6": 92,
            "7": 28,
            "8": 1,
            "image": "images/squirrel.jpg"
        },
        "Rabbit": {
            "1": 0,
            "2": 88,
            "3": 52,
            "4": 12,
            "5": 92,
            "6": 88,
            "7": 22,
            "8": 45,
            "image": "images/rabbit.jpg"
        },
        "Hare": {
            "1": 0,
            "2": 82,
            "3": 68,
            "4": 12,
            "5": 85,
            "6": 82,
            "7": 32,
            "8": 22,
            "image": "images/hare.jpg"
        },
        "Guinea Pig": {
            "1": 0,
            "2": 92,
            "3": 12,
            "4": 8,
            "5": 95,
            "6": 42,
            "7": 18,
            "8": 55,
            "image": "images/guinea_pig.jpg"
        },
        "Hamster": {
            "1": 0,
            "2": 88,
            "3": 8,
            "4": 4,
            "5": 98,
            "6": 65,
            "7": 15,
            "8": 2,
            "image": "images/hamster.jpg"
        },
        "Rat": {
            "1": 2,
            "2": 72,
            "3": 18,
            "4": 4,
            "5": 98,
            "6": 98,
            "7": 25,
            "8": 8,
            "image": "images/rat.jpg"
        },
        "Mouse": {
            "1": 0,
            "2": 75,
            "3": 12,
            "4": 3,
            "5": 98,
            "6": 98,
            "7": 12,
            "8": 1,
            "image": "images/mouse.jpg"
        },
        "Chinchilla": {
            "1": 0,
            "2": 98,
            "3": 15,
            "4": 18,
            "5": 45,
            "6": 12,
            "7": 22,
            "8": 3,
            "image": "images/chinchilla.jpg"
        },
        "Ferret": {
            "1": 0,
            "2": 85,
            "3": 22,
            "4": 12,
            "5": 78,
            "6": 58,
            "7": 38,
            "8": 5,
            "image": "images/ferret.jpg"
        },
        "Mink": {
            "1": 0,
            "2": 95,
            "3": 18,
            "4": 12,
            "5": 65,
            "6": 52,
            "7": 42,
            "8": 12,
            "image": "images/mink.jpg"
        },
        "Fox": {
            "1": 0,
            "2": 88,
            "3": 48,
            "4": 12,
            "5": 78,
            "6": 85,
            "7": 48,
            "8": 8,
            "image": "images/fox.jpg"
        },
        "Jackal": {
            "1": 1,
            "2": 75,
            "3": 52,
            "4": 15,
            "5": 72,
            "6": 68,
            "7": 52,
            "8": 4,
            "image": "images/jackal.jpg"
        },
        "Coyote": {
            "1": 1,
            "2": 78,
            "3": 58,
            "4": 16,
            "5": 82,
            "6": 72,
            "7": 58,
            "8": 6,
            "image": "images/coyote.jpg"
        },
        "Hyena": {
            "1": 2,
            "2": 42,
            "3": 55,
            "4": 25,
            "5": 58,
            "6": 45,
            "7": 72,
            "8": 2,
            "image": "images/hyena.jpg"
        },
        "Warthog": {
            "1": 1,
            "2": 28,
            "3": 48,
            "4": 18,
            "5": 68,
            "6": 42,
            "7": 62,
            "8": 10,
            "image": "images/warthog.jpg"
        },
        "Wild Boar": {
            "1": 4,
            "2": 38,
            "3": 42,
            "4": 22,
            "5": 75,
            "6": 72,
            "7": 68,
            "8": 25,
            "image": "images/wild_boar.jpg"
        },
        "Peccary": {
            "1": 1,
            "2": 42,
            "3": 35,
            "4": 18,
            "5": 72,
            "6": 48,
            "7": 55,
            "8": 8,
            "image": "images/peccary.jpg"
        },
        "Tapir": {
            "1": 0,
            "2": 35,
            "3": 42,
            "4": 38,
            "5": 42,
            "6": 35,
            "7": 72,
            "8": 3,
            "image": "images/tapir.jpg"
        },
        "Aardvark": {
            "1": 0,
            "2": 22,
            "3": 28,
            "4": 28,
            "5": 58,
            "6": 45,
            "7": 62,
            "8": 1,
            "image": "images/aardvark.jpg"
        },
        "Anteater": {
            "1": 0,
            "2": 72,
            "3": 22,
            "4": 25,
            "5": 52,
            "6": 42,
            "7": 58,
            "8": 0,
            "image": "images/anteater.jpg"
        },
        "Sloth": {
            "1": 0,
            "2": 82,
            "3": 1,
            "4": 42,
            "5": 48,
            "6": 28,
            "7": 18,
            "8": 0,
            "image": "images/sloth.jpg"
        },
        "Armadillo": {
            "1": 0,
            "2": 12,
            "3": 32,
            "4": 22,
            "5": 75,
            "6": 62,
            "7": 42,
            "8": 5,
            "image": "images/armadillo.jpg"
        },
        "Pangolin": {
            "1": 0,
            "2": 8,
            "3": 12,
            "4": 22,
            "5": 15,
            "6": 52,
            "7": 38,
            "8": 3,
            "image": "images/pangolin.jpg"
        },
        "Hedgehog": {
            "1": 0,
            "2": 95,
            "3": 8,
            "4": 8,
            "5": 78,
            "6": 72,
            "7": 22,
            "8": 1,
            "image": "images/hedgehog.jpg"
        },
        "Porcupine": {
            "1": 0,
            "2": 98,
            "3": 12,
            "4": 25,
            "5": 72,
            "6": 68,
            "7": 35,
            "8": 2,
            "image": "images/porcupine.jpg"
        },
        "Skunk": {
            "1": 0,
            "2": 88,
            "3": 18,
            "4": 12,
            "5": 82,
            "6": 68,
            "7": 28,
            "8": 1,
            "image": "images/skunk.jpg"
        },
        "Mole": {
            "1": 0,
            "2": 92,
            "3": 5,
            "4": 8,
            "5": 85,
            "6": 75,
            "7": 32,
            "8": 0,
            "image": "images/mole.jpg"
        },
        "Shrew": {
            "1": 0,
            "2": 85,
            "3": 8,
            "4": 3,
            "5": 88,
            "6": 82,
            "7": 22,
            "8": 0,
            "image": "images/shrew.jpg"
        },
        "Bat": {
            "1": 0,
            "2": 68,
            "3": 65,
            "4": 52,
            "5": 85,
            "6": 98,
            "7": 25,
            "8": 0,
            "image": "images/bat.jpg"
        },
        "Peregrine Falcon": {
            "1": 0,
            "2": 72,
            "3": 100,
            "4": 22,
            "5": 68,
            "6": 88,
            "7": 48,
            "8": 0,
            "image": "images/peregrine_falcon.jpg"
        },
        "Golden Eagle": {
            "1": 0,
            "2": 78,
            "3": 98,
            "4": 35,
            "5": 62,
            "6": 75,
            "7": 68,
            "8": 0,
            "image": "images/golden_eagle.jpg"
        },
        "Bald Eagle": {
            "1": 0,
            "2": 82,
            "3": 85,
            "4": 38,
            "5": 55,
            "6": 52,
            "7": 72,
            "8": 0,
            "image": "images/bald_eagle.jpg"
        },
        "Hawk": {
            "1": 0,
            "2": 75,
            "3": 78,
            "4": 25,
            "5": 75,
            "6": 85,
            "7": 52,
            "8": 0,
            "image": "images/hawk.jpg"
        },
        "Owl": {
            "1": 0,
            "2": 92,
            "3": 42,
            "4": 35,
            "5": 82,
            "6": 92,
            "7": 48,
            "8": 0,
            "image": "images/owl.jpg"
        },
        "Vulture": {
            "1": 0,
            "2": 45,
            "3": 72,
            "4": 48,
            "5": 68,
            "6": 78,
            "7": 52,
            "8": 2,
            "image": "images/vulture.jpg"
        },
        "Condor": {
            "1": 0,
            "2": 55,
            "3": 68,
            "4": 65,
            "5": 28,
            "6": 35,
            "7": 58,
            "8": 0,
            "image": "images/condor.jpg"
        },
        "Albatross": {
            "1": 0,
            "2": 82,
            "3": 88,
            "4": 75,
            "5": 52,
            "6": 65,
            "7": 42,
            "8": 0,
            "image": "images/albatross.jpg"
        },
        "Pelican": {
            "1": 0,
            "2": 72,
            "3": 55,
            "4": 32,
            "5": 72,
            "6": 75,
            "7": 48,
            "8": 5,
            "image": "images/pelican.jpg"
        },
        "Cormorant": {
            "1": 0,
            "2": 58,
            "3": 52,
            "4": 28,
            "5": 78,
            "6": 82,
            "7": 38,
            "8": 8,
            "image": "images/cormorant.jpg"
        },
        "Heron": {
            "1": 0,
            "2": 62,
            "3": 48,
            "4": 28,
            "5": 82,
            "6": 85,
            "7": 35,
            "8": 4,
            "image": "images/heron.jpg"
        },
        "Crane": {
            "1": 0,
            "2": 68,
            "3": 58,
            "4": 35,
            "5": 62,
            "6": 68,
            "7": 45,
            "8": 3,
            "image": "images/crane.jpg"
        },
        "Stork": {
            "1": 0,
            "2": 65,
            "3": 62,
            "4": 42,
            "5": 68,
            "6": 72,
            "7": 42,
            "8": 2,
            "image": "images/stork.jpg"
        },
        "Flamingo": {
            "1": 0,
            "2": 72,
            "3": 52,
            "4": 48,
            "5": 72,
            "6": 55,
            "7": 32,
            "8": 1,
            "image": "images/flamingo.jpg"
        },
        "Swan": {
            "1": 1,
            "2": 95,
            "3": 75,
            "4": 32,
            "5": 75,
            "6": 78,
            "7": 52,
            "8": 4,
            "image": "images/swan.jpg"
        },
        "Penguin": {
            "1": 0,
            "2": 88,
            "3": 15,
            "4": 28,
            "5": 68,
            "6": 22,
            "7": 38,
            "8": 6,
            "image": "images/penguin.jpg"
        },
        "Ostrich": {
            "1": 2,
            "2": 65,
            "3": 82,
            "4": 52,
            "5": 62,
            "6": 38,
            "7": 78,
            "8": 12,
            "image": "images/ostrich.jpg"
        },
        "Emu": {
            "1": 1,
            "2": 72,
            "3": 58,
            "4": 38,
            "5": 58,
            "6": 12,
            "7": 68,
            "8": 8,
            "image": "images/emu.jpg"
        },
        "Cassowary": {
            "1": 3,
            "2": 68,
            "3": 48,
            "4": 65,
            "5": 35,
            "6": 8,
            "7": 82,
            "8": 0,
            "image": "images/cassowary.jpg"
        },
        "Kiwi": {
            "1": 0,
            "2": 88,
            "3": 8,
            "4": 42,
            "5": 42,
            "6": 4,
            "7": 18,
            "8": 0,
            "image": "images/kiwi.jpg"
        },
        "Parrot": {
            "1": 0,
            "2": 75,
            "3": 45,
            "4": 82,
            "5": 65,
            "6": 68,
            "7": 28,
            "8": 1,
            "image": "images/parrot.jpg"
        },
        "Macaw": {
            "1": 0,
            "2": 82,
            "3": 52,
            "4": 75,
            "5": 48,
            "6": 38,
            "7": 32,
            "8": 0,
            "image": "images/macaw.jpg"
        },
        "Cockatoo": {
            "1": 0,
            "2": 88,
            "3": 48,
            "4": 78,
            "5": 58,
            "6": 42,
            "7": 35,
            "8": 0,
            "image": "images/cockatoo.jpg"
        },
        "Toucan": {
            "1": 0,
            "2": 68,
            "3": 42,
            "4": 25,
            "5": 62,
            "6": 32,
            "7": 28,
            "8": 0,
            "image": "images/toucan.jpg"
        },
        "Woodpecker": {
            "1": 0,
            "2": 72,
            "3": 32,
            "4": 15,
            "5": 78,
            "6": 78,
            "7": 38,
            "8": 0,
            "image": "images/woodpecker.jpg"
        },
        "Hummingbird": {
            "1": 0,
            "2": 82,
            "3": 68,
            "4": 12,
            "5": 82,
            "6": 72,
            "7": 22,
            "8": 0,
            "image": "images/hummingbird.jpg"
        },
        "Kingfisher": {
            "1": 0,
            "2": 78,
            "3": 55,
            "4": 18,
            "5": 75,
            "6": 75,
            "7": 32,
            "8": 0,
            "image": "images/kingfisher.jpg"
        },
        "Robin": {
            "1": 0,
            "2": 75,
            "3": 38,
            "4": 8,
            "5": 88,
            "6": 85,
            "7": 18,
            "8": 0,
            "image": "images/robin.jpg"
        },
        "Sparrow": {
            "1": 0,
            "2": 72,
            "3": 32,
            "4": 8,
            "5": 95,
            "6": 95,
            "7": 15,
            "8": 0,
            "image": "images/sparrow.jpg"
        },
        "Pigeon": {
            "1": 0,
            "2": 68,
            "3": 95,
            "4": 12,
            "5": 98,
            "6": 98,
            "7": 22,
            "8": 15,
            "image": "images/pigeon.jpg"
        },
        "Dove": {
            "1": 0,
            "2": 72,
            "3": 82,
            "4": 15,
            "5": 92,
            "6": 92,
            "7": 18,
            "8": 8,
            "image": "images/dove.jpg"
        },
        "Crow": {
            "1": 0,
            "2": 65,
            "3": 52,
            "4": 25,
            "5": 88,
            "6": 92,
            "7": 28,
            "8": 1,
            "image": "images/crow.jpg"
        },
        "Raven": {
            "1": 0,
            "2": 68,
            "3": 58,
            "4": 32,
            "5": 82,
            "6": 88,
            "7": 32,
            "8": 0,
            "image": "images/raven.jpg"
        },
        "Magpie": {
            "1": 0,
            "2": 72,
            "3": 42,
            "4": 22,
            "5": 85,
            "6": 82,
            "7": 25,
            "8": 0,
            "image": "images/magpie.jpg"
        },
        "Jay": {
            "1": 0,
            "2": 75,
            "3": 38,
            "4": 18,
            "5": 82,
            "6": 78,
            "7": 22,
            "8": 0,
            "image": "images/jay.jpg"
        },
        "Seagull": {
            "1": 2,
            "2": 68,
            "3": 62,
            "4": 28,
            "5": 92,
            "6": 95,
            "7": 28,
            "8": 3,
            "image": "images/seagull.jpg"
        },
        "Tern": {
            "1": 0,
            "2": 72,
            "3": 75,
            "4": 38,
            "5": 78,
            "6": 85,
            "7": 25,
            "8": 2,
            "image": "images/tern.jpg"
        },
        "Puffin": {
            "1": 0,
            "2": 88,
            "3": 52,
            "4": 32,
            "5": 62,
            "6": 35,
            "7": 28,
            "8": 4,
            "image": "images/puffin.jpg"
        },
        "Salmon": {
            "1": 0,
            "2": 2,
            "3": 42,
            "4": 8,
            "5": 58,
            "6": 52,
            "7": 48,
            "8": 75,
            "image": "images/salmon.jpg"
        },
        "Trout": {
            "1": 0,
            "2": 1,
            "3": 38,
            "4": 12,
            "5": 68,
            "6": 68,
            "7": 42,
            "8": 65,
            "image": "images/trout.jpg"
        },
        "Tuna": {
            "1": 0,
            "2": 0,
            "3": 78,
            "4": 22,
            "5": 48,
            "6": 88,
            "7": 72,
            "8": 85,
            "image": "images/tuna.jpg"
        },
        "Swordfish": {
            "1": 1,
            "2": 0,
            "3": 85,
            "4": 18,
            "5": 52,
            "6": 75,
            "7": 75,
            "8": 55,
            "image": "images/swordfish.jpg"
        },
        "Marlin": {
            "1": 0,
            "2": 0,
            "3": 92,
            "4": 25,
            "5": 45,
            "6": 72,
            "7": 78,
            "8": 22,
            "image": "images/marlin.jpg"
        },
        "Shark (Great White)": {
            "1": 3,
            "2": 3,
            "3": 48,
            "4": 85,
            "5": 28,
            "6": 68,
            "7": 88,
            "8": 5,
            "image": "images/shark_great_white.jpg"
        },
        "Hammerhead Shark": {
            "1": 1,
            "2": 2,
            "3": 42,
            "4": 42,
            "5": 22,
            "6": 72,
            "7": 82,
            "8": 8,
            "image": "images/hammerhead_shark.jpg"
        },
        "Tiger Shark": {
            "1": 2,
            "2": 2,
            "3": 38,
            "4": 55,
            "5": 32,
            "6": 75,
            "7": 85,
            "8": 4,
            "image": "images/tiger_shark.jpg"
        },
        "Whale Shark": {
            "1": 0,
            "2": 1,
            "3": 12,
            "4": 125,
            "5": 18,
            "6": 78,
            "7": 75,
            "8": 2,
            "image": "images/whale_shark.jpg"
        },
        "Orca": {
            "1": 0,
            "2": 5,
            "3": 52,
            "4": 95,
            "5": 38,
            "6": 88,
            "7": 92,
            "8": 3,
            "image": "images/orca.jpg"
        },
        "Dolphin": {
            "1": 1,
            "2": 3,
            "3": 55,
            "4": 58,
            "5": 62,
            "6": 92,
            "7": 72,
            "8": 12,
            "image": "images/dolphin.jpg"
        },
        "Porpoise": {
            "1": 0,
            "2": 4,
            "3": 48,
            "4": 28,
            "5": 55,
            "6": 78,
            "7": 65,
            "8": 8,
            "image": "images/porpoise.jpg"
        },
        "Manatee": {
            "1": 0,
            "2": 8,
            "3": 8,
            "4": 75,
            "5": 25,
            "6": 42,
            "7": 62,
            "8": 1,
            "image": "images/manatee.jpg"
        },
        "Seal": {
            "1": 0,
            "2": 42,
            "3": 32,
            "4": 48,
            "5": 58,
            "6": 68,
            "7": 68,
            "8": 28,
            "image": "images/seal.jpg"
        },
        "Sea Lion": {
            "1": 0,
            "2": 38,
            "3": 35,
            "4": 38,
            "5": 52,
            "6": 62,
            "7": 72,
            "8": 18,
            "image": "images/sea_lion.jpg"
        },
        "Walrus": {
            "1": 1,
            "2": 48,
            "3": 22,
            "4": 52,
            "5": 42,
            "6": 32,
            "7": 85,
            "8": 8,
            "image": "images/walrus.jpg"
        },
        "Polar Bear": {
            "1": 4,
            "2": 98,
            "3": 38,
            "4": 32,
            "5": 22,
            "6": 15,
            "7": 92,
            "8": 0,
            "image": "images/polar_bear.jpg"
        },
        "Panda": {
            "1": 0,
            "2": 95,
            "3": 28,
            "4": 32,
            "5": 18,
            "6": 8,
            "7": 62,
            "8": 0,
            "image": "images/panda.jpg"
        },
        "Grizzly Bear": {
            "1": 8,
            "2": 92,
            "3": 45,
            "4": 35,
            "5": 35,
            "6": 42,
            "7": 88,
            "8": 5,
            "image": "images/grizzly_bear.jpg"
        },
        "Black Bear": {
            "1": 2,
            "2": 88,
            "3": 48,
            "4": 32,
            "5": 58,
            "6": 62,
            "7": 78,
            "8": 3,
            "image": "images/black_bear.jpg"
        },
        "Sun Bear": {
            "1": 0,
            "2": 75,
            "3": 35,
            "4": 28,
            "5": 28,
            "6": 18,
            "7": 65,
            "8": 0,
            "image": "images/sun_bear.jpg"
        },
        "Sloth Bear": {
            "1": 1,
            "2": 82,
            "3": 32,
            "4": 38,
            "5": 32,
            "6": 25,
            "7": 72,
            "8": 0,
            "image": "images/sloth_bear.jpg"
        },
        "Spectacled Bear": {
            "1": 0,
            "2": 85,
            "3": 38,
            "4": 42,
            "5": 25,
            "6": 22,
            "7": 68,
            "8": 0,
            "image": "images/spectacled_bear.jpg"
        },
        "Red Panda": {
            "1": 0,
            "2": 95,
            "3": 35,
            "4": 18,
            "5": 15,
            "6": 12,
            "7": 35,
            "8": 0,
            "image": "images/red_panda.jpg"
        },
        "Meerkat": {
            "1": 0,
            "2": 58,
            "3": 32,
            "4": 15,
            "5": 75,
            "6": 22,
            "7": 28,
            "8": 1,
            "image": "images/meerkat.jpg"
        },
        "Mongoose": {
            "1": 0,
            "2": 62,
            "3": 38,
            "4": 12,
            "5": 82,
            "6": 68,
            "7": 42,
            "8": 2,
            "image": "images/mongoose.jpg"
        },
        "Civet": {
            "1": 0,
            "2": 72,
            "3": 28,
            "4": 22,
            "5": 65,
            "6": 52,
            "7": 45,
            "8": 4,
            "image": "images/civet.jpg"
        },
        "Genet": {
            "1": 0,
            "2": 75,
            "3": 32,
            "4": 18,
            "5": 62,
            "6": 48,
            "7": 38,
            "8": 1,
            "image": "images/genet.jpg"
        },
        "Lynx": {
            "1": 0,
            "2": 88,
            "3": 62,
            "4": 22,
            "5": 48,
            "6": 55,
            "7": 68,
            "8": 3,
            "image": "images/lynx.jpg"
        },
        "Bobcat": {
            "1": 0,
            "2": 82,
            "3": 58,
            "4": 18,
            "5": 62,
            "6": 52,
            "7": 65,
            "8": 2,
            "image": "images/bobcat.jpg"
        },
        "Puma": {
            "1": 2,
            "2": 78,
            "3": 72,
            "4": 22,
            "5": 42,
            "6": 58,
            "7": 75,
            "8": 1,
            "image": "images/puma.jpg"
        },
        "Jaguar": {
            "1": 3,
            "2": 72,
            "3": 65,
            "4": 18,
            "5": 28,
            "6": 35,
            "7": 85,
            "8": 0,
            "image": "images/jaguar.jpg"
        },
        "Snow Leopard": {
            "1": 0,
            "2": 95,
            "3": 58,
            "4": 25,
            "5": 18,
            "6": 28,
            "7": 72,
            "8": 0,
            "image": "images/snow_leopard.jpg"
        },
        "Clouded Leopard": {
            "1": 0,
            "2": 85,
            "3": 52,
            "4": 22,
            "5": 15,
            "6": 22,
            "7": 68,
            "8": 0,
            "image": "images/clouded_leopard.jpg"
        },
        "Ocelot": {
            "1": 0,
            "2": 78,
            "3": 48,
            "4": 18,
            "5": 38,
            "6": 38,
            "7": 58,
            "8": 0,
            "image": "images/ocelot.jpg"
        },
        "Serval": {
            "1": 0,
            "2": 72,
            "3": 72,
            "4": 22,
            "5": 52,
            "6": 42,
            "7": 52,
            "8": 0,
            "image": "images/serval.jpg"
        },
        "Caracal": {
            "1": 0,
            "2": 68,
            "3": 75,
            "4": 22,
            "5": 58,
            "6": 48,
            "7": 62,
            "8": 0,
            "image": "images/caracal.jpg"
        },
        "Fishing Cat": {
            "1": 0,
            "2": 75,
            "3": 35,
            "4": 18,
            "5": 32,
            "6": 22,
            "7": 58,
            "8": 0,
            "image": "images/fishing_cat.jpg"
        },
        "Leopard Cat": {
            "1": 0,
            "2": 78,
            "3": 42,
            "4": 18,
            "5": 62,
            "6": 52,
            "7": 48,
            "8": 0,
            "image": "images/leopard_cat.jpg"
        },
        "Sand Cat": {
            "1": 0,
            "2": 92,
            "3": 38,
            "4": 18,
            "5": 45,
            "6": 32,
            "7": 42,
            "8": 0,
            "image": "images/sand_cat.jpg"
        },
        "Black-footed Cat": {
            "1": 0,
            "2": 88,
            "3": 48,
            "4": 18,
            "5": 38,
            "6": 18,
            "7": 48,
            "8": 0,
            "image": "images/black-footed_cat.jpg"
        },
        "Rusty-spotted Cat": {
            "1": 0,
            "2": 82,
            "3": 38,
            "4": 15,
            "5": 28,
            "6": 12,
            "7": 38,
            "8": 0,
            "image": "images/rusty-spotted_cat.jpg"
        },
        "Octopus": {
            "1": 0,
            "2": 0,
            "3": 35,
            "4": 8,
            "5": 72,
            "6": 85,
            "7": 65,
            "8": 35,
            "image": "images/octopus.jpg"
        },
        "Squid": {
            "1": 0,
            "2": 0,
            "3": 42,
            "4": 5,
            "5": 82,
            "6": 88,
            "7": 58,
            "8": 45,
            "image": "images/squid.jpg"
        },
        "Cuttlefish": {
            "1": 0,
            "2": 0,
            "3": 28,
            "4": 3,
            "5": 75,
            "6": 78,
            "7": 48,
            "8": 28,
            "image": "images/cuttlefish.jpg"
        },
        "Lobster": {
            "1": 0,
            "2": 5,
            "3": 18,
            "4": 95,
            "5": 62,
            "6": 75,
            "7": 62,
            "8": 72,
            "image": "images/lobster.jpg"
        },
        "Crab": {
            "1": 0,
            "2": 4,
            "3": 12,
            "4": 15,
            "5": 88,
            "6": 92,
            "7": 45,
            "8": 68,
            "image": "images/crab.jpg"
        },
        "Shrimp": {
            "1": 0,
            "2": 1,
            "3": 8,
            "4": 4,
            "5": 92,
            "6": 95,
            "7": 22,
            "8": 85,
            "image": "images/shrimp.jpg"
        },
        "Crayfish": {
            "1": 0,
            "2": 3,
            "3": 12,
            "4": 8,
            "5": 82,
            "6": 68,
            "7": 38,
            "8": 42,
            "image": "images/crayfish.jpg"
        },
        "Clam": {
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 550,
            "5": 78,
            "6": 82,
            "7": 12,
            "8": 55,
            "image": "images/clam.jpg"
        },
        "Oyster": {
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 25,
            "5": 72,
            "6": 78,
            "7": 8,
            "8": 78,
            "image": "images/oyster.jpg"
        },
        "Mussel": {
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 275,
            "5": 82,
            "6": 85,
            "7": 15,
            "8": 62,
            "image": "images/mussel.jpg"
        },
        "Scallop": {
            "1": 0,
            "2": 0,
            "3": 8,
            "4": 22,
            "5": 68,
            "6": 72,
            "7": 18,
            "8": 58,
            "image": "images/scallop.jpg"
        },
        "Snail": {
            "1": 0,
            "2": 1,
            "3": 1,
            "4": 18,
            "5": 92,
            "6": 95,
            "7": 8,
            "8": 35,
            "image": "images/snail.jpg"
        },
        "Slug": {
            "1": 0,
            "2": 0,
            "3": 1,
            "4": 8,
            "5": 88,
            "6": 88,
            "7": 5,
            "8": 12,
            "image": "images/slug.jpg"
        },
        "Starfish": {
            "1": 0,
            "2": 0,
            "3": 2,
            "4": 48,
            "5": 78,
            "6": 85,
            "7": 28,
            "8": 8,
            "image": "images/starfish.jpg"
        },
        "Sea Urchin": {
            "1": 2,
            "2": 0,
            "3": 1,
            "4": 225,
            "5": 72,
            "6": 78,
            "7": 18,
            "8": 22,
            "image": "images/sea_urchin.jpg"
        },
        "Sea Cucumber": {
            "1": 0,
            "2": 0,
            "3": 1,
            "4": 12,
            "5": 68,
            "6": 75,
            "7": 12,
            "8": 28,
            "image": "images/sea_cucumber.jpg"
        },
        "Coral": {
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 4500,
            "5": 45,
            "6": 68,
            "7": 5,
            "8": 0,
            "image": "images/coral.jpg"
        }
    }
};